// Generated by gencpp from file open_manipulator_with_tb3_msgs/PickRequest.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PICKREQUEST_H
#define OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PICKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_manipulator_with_tb3_msgs
{
template <class ContainerAllocator>
struct PickRequest_
{
  typedef PickRequest_<ContainerAllocator> Type;

  PickRequest_()
    : state()  {
    }
  PickRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PickRequest_

typedef ::open_manipulator_with_tb3_msgs::PickRequest_<std::allocator<void> > PickRequest;

typedef boost::shared_ptr< ::open_manipulator_with_tb3_msgs::PickRequest > PickRequestPtr;
typedef boost::shared_ptr< ::open_manipulator_with_tb3_msgs::PickRequest const> PickRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace open_manipulator_with_tb3_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_with_tb3_msgs/PickRequest";
  }

  static const char* value(const ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n\
";
  }

  static const char* value(const ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_with_tb3_msgs::PickRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PICKREQUEST_H
