// Generated by gencpp from file open_manipulator_with_tb3_msgs/Place.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PLACE_H
#define OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PLACE_H

#include <ros/service_traits.h>


#include <open_manipulator_with_tb3_msgs/PlaceRequest.h>
#include <open_manipulator_with_tb3_msgs/PlaceResponse.h>


namespace open_manipulator_with_tb3_msgs
{

struct Place
{

typedef PlaceRequest Request;
typedef PlaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Place
} // namespace open_manipulator_with_tb3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_with_tb3_msgs::Place > {
  static const char* value()
  {
    return "1c3e9cad628ebe29faeb3b4f60a0626c";
  }

  static const char* value(const ::open_manipulator_with_tb3_msgs::Place&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_with_tb3_msgs::Place > {
  static const char* value()
  {
    return "open_manipulator_with_tb3_msgs/Place";
  }

  static const char* value(const ::open_manipulator_with_tb3_msgs::Place&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_with_tb3_msgs::PlaceRequest> should match 
// service_traits::MD5Sum< ::open_manipulator_with_tb3_msgs::Place > 
template<>
struct MD5Sum< ::open_manipulator_with_tb3_msgs::PlaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_with_tb3_msgs::Place >::value();
  }
  static const char* value(const ::open_manipulator_with_tb3_msgs::PlaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_with_tb3_msgs::PlaceRequest> should match 
// service_traits::DataType< ::open_manipulator_with_tb3_msgs::Place > 
template<>
struct DataType< ::open_manipulator_with_tb3_msgs::PlaceRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_with_tb3_msgs::Place >::value();
  }
  static const char* value(const ::open_manipulator_with_tb3_msgs::PlaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_with_tb3_msgs::PlaceResponse> should match 
// service_traits::MD5Sum< ::open_manipulator_with_tb3_msgs::Place > 
template<>
struct MD5Sum< ::open_manipulator_with_tb3_msgs::PlaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_with_tb3_msgs::Place >::value();
  }
  static const char* value(const ::open_manipulator_with_tb3_msgs::PlaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_with_tb3_msgs::PlaceResponse> should match 
// service_traits::DataType< ::open_manipulator_with_tb3_msgs::Place > 
template<>
struct DataType< ::open_manipulator_with_tb3_msgs::PlaceResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_with_tb3_msgs::Place >::value();
  }
  static const char* value(const ::open_manipulator_with_tb3_msgs::PlaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_WITH_TB3_MSGS_MESSAGE_PLACE_H
